[package]
name = "motion-photo-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kamadak-exif = "0.5.5"
xmp_toolkit = "1.3.0"
jfifdump = "0.3.2"
